---
- name: "Ansible Docker"
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Install aptitude using apt
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

  - name: Install required system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Update apt and install docker-ce
    apt: update_cache=yes name=docker-ce state=latest

  - name: Install Docker Module for Python
    pip:
      name: docker

    #Fazendo o Pull na maquina de destino
  - name: Docker Pull Application
    docker_image:
      name: ewertonely/laravel-blog:latest
      source: pull

    #Iniciando a nova versão da aplicação
  - name: Start Application 
    docker_container:
      name: laravelcami
      image: ewertonely/laravel-blog:latest
      recreate: yes
      published_ports:
        - 80:80

  - name: Waiting Aplication Starting Up
    uri:
      url: "http://localhost"
      follow_redirects: none
      method: GET
    register: result
    until: result.status == 200
    retries: 24 # 24 * 5 segundos = 2 minutos
    delay: 5 # A cada 5 segundos