---
- name: "Ansible Playbook"
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:

    # Build usando o ansible
    # - name: Build Aplication
    #   shell: "docker build -t mauriciopgomes/frango_frito ."

    #Enviando para o Registry (Docker-hub) usando o Ansible
    # - name: Push to Registry 
    #   shell: "docker push mauriciopgomes/frango_frito:latest"

    #Fazendo o Pull na maquina de destino
    - name: Docker Pull Application
      docker_image:
        name: mauriciopgomes/frango_frito:latest
        source: pull

    #Iniciando a nova versão da aplicação
    - name: Start Application 
      docker_container:
        name: frango_veloz
        image: mauriciopgomes/frango_frito:latest
        recreate: yes
        published_ports:
          - 80:80

    - name: Aguardando a Aplicação subir
      uri:
        url: "http://localhost"
        follow_redirects: none
        method: GET
      register: result
      until: result.status == 200
      retries: 24 # 24 * 5 segundos = 2 minutos
      delay: 5 # A cada 5 segundos