---
- name: "Ansible Docker"
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Add extras repository
    shell: yum-config-manager --enable extras
    become: yes
    become_user: root

  - name: Install docker-ce (centos) via amazon-linux-extras packages
    shell: "amazon-linux-extras install docker=18.06.1 -y"
    become: yes
    become_user: root

  - name: Enable Docker CE service at startup
    service:
      name: docker
      state: started
      enabled: yes
    become: yes
    become_user: root

    #Fazendo o Pull na maquina de destino
  - name: Docker Pull Application
    docker_image:
      name: ewertonely/laravel-blog:latest
      source: pull

    #Iniciando a nova versão da aplicação
  - name: Start Application 
    docker_container:
      name: laravelcami
      image: ewertonely/laravel-blog:latest
      recreate: yes
      published_ports:
        - 80:80

  - name: Waiting Aplication Starting Up
    uri:
      url: "http://localhost"
      follow_redirects: none
      method: GET
    register: result
    until: result.status == 200
    retries: 24 # 24 * 5 segundos = 2 minutos
    delay: 5 # A cada 5 segundos